-- MySQL Script generated by MySQL Workbench
-- Fri Nov 29 19:38:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionário` (
  `CodFuncionário` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `DataContratação` DATE NOT NULL,
  `TipodeFuncionário` VARCHAR(45) NULL,
  PRIMARY KEY (`CodFuncionário`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gerente` (
  `Departamento` VARCHAR(45) NOT NULL,
  `Nível de Gestão` VARCHAR(45) NOT NULL,
  `CodGerente` INT NOT NULL,
  PRIMARY KEY (`CodGerente`),
  CONSTRAINT `pk_Gerente_Funcionario`
    FOREIGN KEY (`CodGerente`)
    REFERENCES `mydb`.`Funcionário` (`CodFuncionário`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `codEvento` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `N° de Participantes` INT NOT NULL,
  `codOrganizador` INT NOT NULL,
  PRIMARY KEY (`codEvento`),
  INDEX `pk_Gerente_Evento_idx` (`codOrganizador` ASC) VISIBLE,
  CONSTRAINT `pk_Gerente_Evento`
    FOREIGN KEY (`codOrganizador`)
    REFERENCES `mydb`.`Gerente` (`CodGerente`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prato` (
  `CodPrato` INT NOT NULL,
  `Tempo de Preparo` DATETIME NOT NULL,
  `Preço` DECIMAL(3,2) NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodPrato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `CodCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  `Número de Fidelidade` INT NOT NULL,
  PRIMARY KEY (`CodCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mesa` (
  `Número` INT NOT NULL,
  `Capacidade` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Número`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `CodFornecedor` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CodFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atendente` (
  `Turno de Trabalho` VARCHAR(45) NULL,
  `IdAtendente` INT NOT NULL,
  PRIMARY KEY (`IdAtendente`),
  CONSTRAINT `funAtendenteCod`
    FOREIGN KEY (`IdAtendente`)
    REFERENCES `mydb`.`Funcionário` (`CodFuncionário`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `CodPedido` INT NOT NULL,
  `Data/Hora` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `n°Mesa` INT NOT NULL,
  `CodCliente` INT NOT NULL,
  `CodAtendente` INT NOT NULL,
  PRIMARY KEY (`CodPedido`),
  INDEX `fk_Pedido_Mesa_idx` (`n°Mesa` ASC) VISIBLE,
  INDEX `fk_Pedido_Cliente_idx` (`CodCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Atendente_idx` (`CodAtendente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Mesa`
    FOREIGN KEY (`n°Mesa`)
    REFERENCES `mydb`.`Mesa` (`Número`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`CodCliente`)
    REFERENCES `mydb`.`Cliente` (`CodCliente`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Atendente`
    FOREIGN KEY (`CodAtendente`)
    REFERENCES `mydb`.`Atendente` (`IdAtendente`)
    ON DELETE NO ACTION
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingrediente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingrediente` (
  `CodIngrediente` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Unidade de Medida` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Data de Validade` DATE NOT NULL,
  PRIMARY KEY (`CodIngrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cozinheiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cozinheiro` (
  `Especialização` VARCHAR(45) NOT NULL,
  `IdCozinheiro` INT NOT NULL,
  `CodChef` INT NULL,
  PRIMARY KEY (`IdCozinheiro`),
  INDEX `pk_Cozinheiro_Cozinheiro_idx` (`CodChef` ASC) VISIBLE,
  CONSTRAINT `pk_Cozinheiro_Funcionario`
    FOREIGN KEY (`IdCozinheiro`)
    REFERENCES `mydb`.`Funcionário` (`CodFuncionário`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_Cozinheiro_Cozinheiro`
    FOREIGN KEY (`CodChef`)
    REFERENCES `mydb`.`Cozinheiro` (`IdCozinheiro`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Preparo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Preparo` (
  `CodIngrediente` INT NOT NULL,
  `CodPrato` INT NOT NULL,
  PRIMARY KEY (`CodIngrediente`, `CodPrato`),
  INDEX `pk_Preparo_Prato_idx` (`CodPrato` ASC) VISIBLE,
  CONSTRAINT `pk_Preparo_Prato`
    FOREIGN KEY (`CodPrato`)
    REFERENCES `mydb`.`Prato` (`CodPrato`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_Preparo_Ingrediente`
    FOREIGN KEY (`CodIngrediente`)
    REFERENCES `mydb`.`Ingrediente` (`CodIngrediente`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecimento` (
  `CodFornecedor` INT NOT NULL,
  `CodIngrediente` INT NOT NULL,
  PRIMARY KEY (`CodFornecedor`, `CodIngrediente`),
  INDEX `pk_Fornecimento_Ingrediente_idx` (`CodIngrediente` ASC) VISIBLE,
  CONSTRAINT `pk_Fornecimento_Fornecedor`
    FOREIGN KEY (`CodFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`CodFornecedor`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_Fornecimento_Ingrediente`
    FOREIGN KEY (`CodIngrediente`)
    REFERENCES `mydb`.`Ingrediente` (`CodIngrediente`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `CodPedido` INT NOT NULL,
  `CodPrato` INT NOT NULL,
  PRIMARY KEY (`CodPedido`, `CodPrato`),
  INDEX `pk_Item_Prato_idx` (`CodPrato` ASC) VISIBLE,
  CONSTRAINT `pk_Item_Pedido`
    FOREIGN KEY (`CodPedido`)
    REFERENCES `mydb`.`Pedido` (`CodPedido`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_Item_Prato`
    FOREIGN KEY (`CodPrato`)
    REFERENCES `mydb`.`Prato` (`CodPrato`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionário/Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionário/Evento` (
  `CodFuncionário` INT NOT NULL,
  `CodEvento` INT NOT NULL,
  PRIMARY KEY (`CodFuncionário`, `CodEvento`),
  INDEX `pk_Evento_Trabalho_idx` (`CodEvento` ASC) VISIBLE,
  CONSTRAINT `pk_Funcionario_Trabalho`
    FOREIGN KEY (`CodFuncionário`)
    REFERENCES `mydb`.`Funcionário` (`CodFuncionário`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `pk_Evento_Trabalho`
    FOREIGN KEY (`CodEvento`)
    REFERENCES `mydb`.`Evento` (`codEvento`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
